#
# Makefile
#
# Trabalho 1
# Estrutura de Dados 1
#

wiked: testador.c Contribuicao.c Editor.c ListaLink.c Pagina.c ListaEditor.c ListaPagina.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -Wno-unused-const-variable -o wiked.out *.c

clean:
	rm -f *.o a.out core wiked.out *.txt
